# versionは3系が最新版で、versionによって書き方が異なる
version: "3"
services:
  mysql:
    build: ./mysql/    #Dockerfileからビルドすることを示す
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d  #初期データをマウントする場所
    image: original_mysql_world # イメージの名前
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password   #コンテナ内のMySQLを起動する際のパスワードを設定
  tomcat:
    build: ./tomcat
    image: mycalcapp
    ports:
      - "8888:8080"
    volumes:
      - ./tomcat/share/logs:/share/logs


#入力してください(docker-compose.ymlがあるディレクトリで)
#docker-compose build
#docker-compose up -d
#docker-compose ps

#次のURLにアクセスすると電卓が利用できます
#http://localhost:8888/sample/calc.jsp

#終わるとき
#docker-compose down
#イメージは残るので，手動で削除してください